<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Borrar Tasca</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>

    <?php include "../app/views/layouts/loginHeader.php"; ?>
    
    <div class="flex justify-center items-center h-screen -mt-20"> 

        <label class="bg-gray-200 py-2 px-4 rounded font-bold" name="menu">Dades incorrectes</label>

    </div>

    <?php include "../app/views/layouts/footer.php"; ?>

</body>
</html>