<div class="container h-screen">
<p class=" text-lg leading-relaxed text-gray-700 bg-gray-100 p-6 rounded-lg shadow-md hover:shadow-lg transition-shadow duration-300 mx-auto max-w-xl">
    Bienvenido a <span class="font-semibold text-blue-600">TaskMaster</span>, tu asistente personal para la gestión de tareas. En esta plataforma, puedes crear, leer, actualizar y eliminar tareas de manera eficiente y sencilla. No más olvidos ni listas en papel que se pierden. Con <span class="font-semibold text-blue-600">TaskMaster</span>, todo lo que necesitas para mantenerte organizado está al alcance de tu mano. Ya sea que estés planeando tu día, semana, o incluso mes, te ofrecemos las herramientas para que lo hagas de la manera más intuitiva posible. Empieza hoy mismo a mejorar tu productividad y a enfocarte en lo que realmente importa. ¡Organiza, planifica y conquista tus tareas con <span class="font-semibold text-blue-600">TaskMaster</span>!
</p>
</div>

