<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Menu</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>

<?php include "../app/views/layouts/header.php"; ?>

<main class="flex justify-center items-center h-screen -mt-20">
    <form action="options" method="post" class="flex flex-col items-center">
        <div class="flex flex-col items-center">
            <label class="bg-gray-200 py-2 px-4 rounded font-bold mb-5" name="menu">Selecciona la opción deseada</label>
            
            <div class="flex flex-row items-center gap-2">
                <button class="bg-blue-500 text-white font-bold py-2 px-4 rounded" name="crear">Crear</button>
                <button class="bg-blue-500 text-white font-bold py-2 px-4 rounded" name="llistar">Llistar</button>
            </div>
        </div>
    </form>
</main>


<?php include "../app/views/layouts/footer.php";?>

</body>
</html>