<?php $tarea = $this->tarea;  $tareaId = $this->tareaId; ?>

<script>
    function mostrarAlertaActualizacion() {
        alert('La tarea ha sido actualizada');
        return true; // Esto permite que el formulario continúe con el proceso de envío.
    }
</script>

<div class="flex justify-center items-center h-screen flex-col">
  <h2 class="text-center mb-6 mt-4 font-bold text-2xl "> Actualitzar la tasca :</h2>
    <input type="hidden" name="tareaId" value="<?= $tareaId ?>">
    <form method="POST" action="" class="w-3/4 md:w-1/2 lg:w-1/3 bg-blue-200 p-8 rounded shadow">
    <p class="font-bold mb-2">Introdueix l'autor de la tasca</p>
        <input type="text" name="autor" value="<?= $tarea['autor'] ?>" class="w-full px-3 py-2 rounded mb-2 border border-gray-300 focus:outline-none focus:border-blue-500" required>
    <p class="font-bold mb-2">Introdueix el títol de la tarea</p>

        <input type="text" name="titulo" value="<?= $tarea['nom_tasques'] ?>" class="w-full px-3 py-2 rounded mb-2 border border-gray-300 focus:outline-none focus:border-blue-500" required>
    <p class="font-bold mb-2">Introdueix la descripcio de la tasca</p>
    
        <input type="text" name="descripcio" id="descripcio" value="<?= $tarea['descrip_tasques'] ?>" class="w-full px-3 py-2 rounded mb-2 border border-gray-300 focus:outline-none focus:border-blue-500" required>
    <p class="font-bold mb-2">Estat</p>
    <div class="mb-4">
            
        <label class="inline-flex items-center">
            <input type="radio" name="estat" value="Pendent" <?= $tarea['estat_tasques'] == 'Pendent' ? 'checked' : '' ?>  checked class="form-radio text-blue-500 focus:ring-blue-500">
            <span class="ml-2">Pendent</span>
        </label>
        <label class="inline-flex items-center">
            <input type="radio" name="estat" value="Actiu" <?= $tarea['estat_tasques'] == 'Actiu' ? 'checked' : '' ?>  required class="form-radio text-blue-500 focus:ring-blue-500">
            <span class="ml-2">Actiu</span>
        </label>
        <label class="inline-flex items-center">
            <input type="radio" name="estat" value="Finalitzat" <?= $tarea['estat_tasques'] == 'Finalitzat' ? 'checked' : '' ?>  class="form-radio text-blue-500 focus:ring-blue-500">
            <span class="ml-2">Finalitzat</span>
        </label>
    </div>       
    
        <input type="submit" onclick="return mostrarAlertaActualizacion()" value="Actualitzar" name="update" class="w-full bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded">
  </form>
 
  
</div>