<div class="flex justify-center items-center h-screen flex-col">
  <h2 class="text-center mb-4">Seleccioneu una tasca per actualitzar:</h2>
  
    <form method="POST" action="updateTasca" class="w-3/4 md:w-1/2 lg:w-1/3 bg-gray-100 p-8 rounded shadow">
    <select name="idTarea" class="w-full bg-white border border-gray-300 p-2 rounded mb-4">
      <option value="">Seleccioneu una tasca</option>
      <?php foreach ($_SESSION['data']['tasques'] as $tarea) {
          echo '<option value="' . $tarea['idTasques'] . '">' . $tarea['idTasques'] . ' - ' . $tarea['nom_tasques'] . '</option>';
      }?>
    </select>
    <input type="submit" class="w-full bg-blue-500 text-white font-bold py-2 px-4 rounded" value="Actualitzar"
    onclick="return confirm('Esteu segur que voleu actualitzar aquesta tasca?')">
  </form>

</div>

 