 <div class="flex justify-center items-center h-screen -mt-20"> 

    <label class="bg-gray-200 py-2 px-4 rounded font-bold" name="menu">
        <h2 class="text-center mb-4">S'ha afegit la tasca a la base de dades</label>
    <a href="menu">
        <button class="flex justify-center items-center bg-blue-500 text-white font-bold py-2 px-4 rounded ml-5" name="inicio">
            Tornar
        </button></a>

</div>
