<!DOCTYPE html>
<html>
<head>
    <title>Borrar Tarea</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>

<?php include "../app/views/layouts/header.php"; ?>

    <h2>Seleccione una tarea para borrar:</h2>
    <form method="POST" action="borrarTasca">
        <select name="idTarea">
            <option value="">Seleccione una tarea</option>
            <?php
            
            
foreach ($_SESSION['data']['tasques'] as $tarea) {
    echo '<option value="' . $tarea['idTasques'] . '">' . $tarea['idTasques'] . ' - ' . $tarea['nom_tasques'] . '</option>';
  }   ?>


        </select>
        <br>
        <input type="submit" value="Borrar" > <!-- onclick="return confirm('¿Estás seguro de que quieres borrar esta tarea?')"> --> 
    </form>


    <?php include "../app/views/layouts/footer.php"; ?>
</body>
</html>