<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index Crear Tasca</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>

<?php include '../app/views/layouts/header.php';?>

<div class="flex justify-center items-center h-screen bg-gray-100">
    <form name="ALTA" method="post" action="addTasca" class="w-full px-3 py-2 rounded mb-2 border-gray-300 focus:outline-none focus:border-blue-500">
    <p class="font-bold mb-2">Introdueix el ID de la tasca</p>
        <input type="number" name="idTasques" class="w-full px-3 py-2 rounded mb-2 border border-gray-300 focus:outline-none focus:border-blue-500" required>
    <p class="font-bold mb-2">Introdueix el titulo de la tarea</p>
        <input type="text" name="titulo" class="w-full px-3 py-2 rounded mb-2 border border-gray-300 focus:outline-none focus:border-blue-500" required>
    <p class="font-bold mb-2">Introdueix la descripcio de la tasca</p>
        <input type="text" name="descripcio" id="descripcio" class="w-full px-3 py-2 rounded mb-2 border border-gray-300 focus:outline-none focus:border-blue-500" required>
        <p class="font-bold mb-2">Introdueix la data d'inici</p>
            <input type="date" name="dataInici" id="dataInici" class="w-full px-3 py-2 rounded mb-2 border border-gray-300 focus:outline-none focus:border-blue-500" required>
        <p class="font-bold mb-2">Introdueix la data fi</p>
            <input type="date" name="dataFi" id="dataFi" class="w-full px-3 py-2 rounded mb-2 border border-gray-300 focus:outline-none focus:border-blue-500">
        <p class="font-bold mb-2">Estat</p>
            <input type="text" name="estat" class="w-full px-3 py-2 rounded mb-4 border border-gray-300 focus:outline-none focus:border-blue-500">
        <br><br>
        <input type="submit" value="Confirmar" class="w-full bg-blue-500 text-white font-bold py-2 px-4 rounded">
    </form>
</div>

<?include '../app/views/layouts/footer.php'?>;
</body>
</html>