<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear Tasca</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>

    <?php include "../app/views/layouts/header.php"; ?>
    
    <div class="flex justify-center items-center h-screen -mt-20"> 

        <label class="bg-gray-200 py-2 px-4 rounded font-bold" name="menu">S'ha borrat la tasca a la base de dades</label>
        <a href="menu"><button class="flex justify-center items-center bg-blue-500 text-white font-bold py-2 px-4 rounded ml-5"
         name="inicio">Tornar</button></a>

    </div>

    <?php include "../app/views/layouts/footer.php"; ?>

</body>
</html>