<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
<?php
include '../app/views/layouts/header.php';

// $data = json_decode(file_get_contents('../../../persistencia/usuarios.json'), true);
?>

<table class="border-collapse w-full h-screen">
    <thead>
        <tr>
            <th class="px-2 py-1 border">Tasca ID</th>
            <th class="px-2 py-1 border">Titol</th>
            <th class="px-2 py-1 border">Descripció</th>
            <th class="px-2 py-1 border">Estat</th>
            <th class="px-2 py-1 border">Data Inici</th>
            <th class="px-2 py-1 border">Data Fi</th>
            <th class="px-2 py-1 border">ID usuari</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($data['tasques'] as $task): ?>
            <tr>
                <td class="px-2 py-1 border w-auto text-center"><?= $task['idTasques'] ?></td>
                <td class="px-2 py-1 border w-auto text-center"><?= $task['nom_tasques'] ?></td>
                <td class="px-2 py-1 border w-auto text-center"><?= $task['descrip_tasques'] ?></td>
                <td class="px-2 py-1 border w-auto text-center"><?= $task['estat_tasques'] ?></td>
                <td class="px-2 py-1 border w-auto text-center"><?= $task['inici_tasques'] ?></td>
                <td class="px-2 py-1 border w-auto text-center"><?= $task['fi_tasques'] ?></td>
                <td class="px-2 py-1 border w-auto text-center"><?= $task['Usuario_idUsuario'] ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php
include '../app/views/layouts/header.php';
?>

</body>
</html>
