<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Llistar Tasques</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>

<?php include "../app/views/layouts/header.php";?>

<body>

<div class="flex h-screen justify-center items-center -mt-20">
    
    <?php
            
    echo '<table class="flex h-screen justify-center items-center -mt-20"';
    echo '<tr><th class="border border-slate-700 p-3 bg-blue-500 text-white font-bold">ID</th><th class="border border-slate-700 p-3 bg-blue-500 text-white font-bold">Nom</th><th class="border border-slate-700 p-3 bg-blue-500 text-white font-bold">Descripció</th><th class="border border-slate-700 p-3 bg-blue-500 text-white font-bold">Estat</th><th class="border border-slate-700 p-3 bg-blue-500 text-white font-bold">Data Inici</th><th class="border border-slate-700 p-3 bg-blue-500 text-white font-bold">Data fi</th></tr>';
        
    while ($resultado = mysqli_fetch_array($_SESSION['tasques'])){

    echo '<tr align="center">';
    echo '<td class="border border-slate-700 rounded-lg p-5 font-bold">';
    echo $resultado['idTasques'];
    echo '</td>';
    echo '<td class="border border-slate-700 rounded-lg p-5">';
    echo $resultado['nom_tasques'];
    echo '</td>';
    echo '<td class="border border-slate-700 rounded-lg p-5">';
    echo $resultado['descrip_tasques'];
    echo '</td>';
    echo '<td class="border border-slate-700 rounded-lg p-5">';
    echo $resultado['estat_tasques'];
    echo '</td>';
    echo '<td class="border border-slate-700 rounded-lg p-5">';
    echo $resultado['inici_tasques'];
    echo '</td>';
    echo '<td class="border border-slate-700 rounded-lg p-5">';
                
        if($resultado['fi_tasques']==="0000-00-00 00:00:00"){

            $resultado['fi_tasques'] = "-";

        }

        echo $resultado['fi_tasques'];

    echo '</td>';
    echo '</tr>';

    }    

    echo '</table>'; 

    ?>
</div>

<?php include "../app/views/layouts/footer.php";?>

</body>
</html>