<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>

<?php include "../app/views/layouts/header.php"; ?>

<section>
    <table class="border-collapse w-80% h-50% center mx-auto">
    <thead>
        <tr>
            <th class="px-2 py-1 border">Tasca ID</th>
            <th class="px-2 py-1 border">Titol</th>
            <th class="px-2 py-1 border">Descripció</th>
            <th class="px-2 py-1 border">Estat</th>
            <th class="px-2 py-1 border">Data Inici</th>
            <th class="px-2 py-1 border">Data Fi</th>
            <th class="px-2 py-1 border">ID usuari</th>
        </tr>
    </thead>
    <tbody>
        <?php 
            
        foreach ($_SESSION['data']['tasques'] as $task): ?>
            <tr>
                <td class="px-2 py-1 border w-auto text-center"><?= $task['idTasques'] ?></td>
                <td class="px-2 py-1 border w-auto text-center"><?= $task['nom_tasques'] ?></td>
                <td class="px-2 py-1 border w-auto text-center"><?= $task['descrip_tasques'] ?></td>
                <td class="px-2 py-1 border w-auto text-center"><?= $task['estat_tasques'] ?></td>
                <td class="px-2 py-1 border w-auto text-center"><?= $task['inici_tasques'] ?></td>
                <td class="px-2 py-1 border w-auto text-center"><?= $task['fi_tasques'] ?></td>
                <td class="px-2 py-1 border w-auto text-center"><?= $task['Usuario_idUsuario'] ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
</section>

<section class="flex justify-center items-center h-screen -mt-20">
    <form action="modificarOpcions" method="post" class="flex flex-col items-center">
        <div class="flex flex-col items-center">
            <label class="bg-gray-200 py-2 px-4 rounded font-bold mb-5" name="menu">Selecciona la opción deseada</label>
            
            <div class="flex flex-row items-center gap-2">
                <button class="bg-blue-500 text-white font-bold py-2 px-4 rounded" name="borrar">Borrar tasca</button>
                <button class="bg-blue-500 text-white font-bold py-2 px-4 rounded" name="actualitzar">Actualitzar tasca</button>
            </div>
        </div>
    </form>
        </section>

<?php include "../app/views/layouts/footer.php";?>

</body>
</html>