<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<script src="https://cdn.tailwindcss.com"></script>
</head>
<body>

<header>
	<nav class="bg-blue-500 p-4">
		<div class="flex justify-between items-center">
			<div>
				<a href="https://cibernarium.barcelonactiva.cat/it-academy/inscripcio;jsessionid=44A52BE7E44A35C9674C0DA90890BF48"
				class="text-white text-lg font-bold hover:text-blue-200 px-4">IT Academy</a>
			</div>
			<nav>
				<a href="menu" class="text-white hover:text-blue-200 px-4">Tornar al menu</a>
				<a href="#" class="text-white hover:text-blue-200 px-4">Nosaltres</a>
				<a href="#" class="text-white hover:text-blue-200 px-4">Serveis</a>
				<a href="#" class="text-white hover:text-blue-200 px-4">Contacte</a>
			</nav>
		</div>
		
		<?php
	if (isset($_SESSION['usuarios']) && isset($_SESSION['usuarios'][0]['idUsuario'])) {
		$idUsuario = $_SESSION['usuarios'][0]['idUsuario'];
		} else {
			$idUsuario = null;
		}

		echo '<div class="flex justify-center items-center">';
		echo '<span class="text-white">Usuari a la sessió  actual: ID ' . $idUsuario . '</span>';
		echo '</div>';
		?>
	</nav>
</header>

<main>
	<?php echo $this->content(); ?>
</main>
	
<footer class="bg-blue-500 text-white text-center py-4">
  <p>Projecte d'Abel i Bryan</p>
  <span>Spring 3 del itinerari Fullstack PHP, IT Academy 2023</span>
</footer>


</body>
</html>