<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap" rel="stylesheet">
    <script src="https://cdn.tailwindcss.com"></script>
</head>

<body class="font-inter bg-gray-50">

    <header>
        <nav class="bg-blue-500 p-4 shadow-md">
            <div class="container mx-auto max-w-7xl flex justify-between items-center">

                <!-- Logo o nombre del sitio -->
                <div>
                    <a href="<?= $this->baseUrl() ?>"
                       class="text-white text-lg font-bold hover:text-blue-200 transition duration-200 ease-in-out px-4">TaskMaster</a>
                </div>

                <!-- Formulario y botones -->
                <div class="flex items-center">
                    <form action="options" method="post" class="flex items-center">
                        <button class="bg-blue-500 text-white font-bold py-1 px-3 rounded-lg hover:bg-blue-700 transition duration-200 ease-in-out mr-2" name="crear">Crear</button>
                        <button class="bg-blue-500 text-white font-bold py-1 px-3 rounded-lg hover:bg-blue-700 transition duration-200 ease-in-out" name="llistar">Llistar</button>
                    </form>
                </div>

            </div>
        </nav>
    </header>

    <main class="py-8">
        <?php echo $this->content(); ?>
    </main>

    <footer class="bg-blue-500 text-white text-center py-4 mt-8">
        <p class="mb-2">Projecte d'Abel i Bryan</p>
        <span>Spring 3 del itinerari Fullstack PHP, IT Academy 2023</span>
    </footer>

</body>

</html>
